### ISSUE TITLE
Pattern generated from MOV instruction contains offset

### ISSUE THREAD

**Issue by pagabuc** [binarly-io/fwhunt-ida#4]
As discussed in this comment: https://github.com/binarly-io/binarly-test-firmware/pull/2#issuecomment-1831885924

The mentioned mov instruction is at address `0x5D3E0`:
[AMITSE.bin.zip](https://github.com/binarly-io/fwhunt-ida/files/13500970/AMITSE.bin.zip)

**Comment by yeggor** [comment]
thank you, fixed:

```
  code:
    and:
      - pattern: 80f9..75..410fb6c2488d4a..41fec249898cc7........e9
          # 80f9c4                              cmp     cl, 0C4h
          # 7518                                jnz     short loc_5D3ED
          # 410fb6c2                            movzx   eax, r10b
          # 488d4a04                            lea     rcx, [rdx+4]
          # 41fec2                              inc     r10b
          # 49898cc760650900                    mov     rva qword_96560[r15+rax*8], rcx
          # e982000000                          jmp     loc_5D46F
```
